#+author: Nícolas André da Costa Morazotti
#+title: Lista Suplementar 1
#+exclude_tags: noexport
#+options: toc:nil
* preamble :noexport:
#+latex_header: \usepackage{tikz}
#+language:pt
#+latex_header: \usepackage[AUTO]{babel}
#+latex_header: \usepackage[margin=1in]{geometry}
#+latex_header: \usepackage{subcaption}
* Questão 1
É dado um sistema cartesiano $\hat x$, $\hat y$, $\hat z$. Um fio reto
infinito, de raio $a$ muito pequeno, se estende de $z=-\infty$ a
$z=\infty$. Calcule o campo elétrico num ponto P a uma distância $r>a$ do
fio. /Sugestão. Considere uma superfície imaginária cilíndrica cujo/
/eixo coincide com o eixo $z$, com raio $r$ e comprimento $L$ qualquer,/
/de forma que o ponto $P$ esteja na superfície cilíndrica. Argumente que o/
/campo elétrico em $P$ tem de ser perpendicular ao eixo z e/
/radial. Aplique em seguida a Lei de Gauss à superfície cilíndrica./

#+BEGIN_EXPORT latex
\begin{figure}[h!]
  \centering
  \begin{tikzpicture}
    \draw (0,0,0) circle (.2);
    \draw[dashed] (0,0,0) circle (1);
    \draw (-0.1,.17,0) -- (-0.1,.17,-4);
    \draw[dashed] (-0.6,0.8,0) -- (-0.5,0.9,-4);
    \draw (0.1,-.17,0) -- (0.1,-.17,-4);
    \draw[dashed] (0.8,-0.6,0) -- (0.9,-0.5,-4);
    \draw (0,0,-4) circle (.2);
    \draw[dashed] (0,0,-4) circle (1);
    \draw[->] (0,0,0) -- (0,0,3) node[left] {$z$};
    \filldraw[black] (-0.4,1,-1) circle (2pt) node[left] {$P$}
  \end{tikzpicture}
  \caption{Diagrama do exercício 1.}
  \label{fig:ex-1}
\end{figure}
#+END_EXPORT

Então, seja uma superfície gaussiana cilíndrica de raio $r>a$, de
comprimento L. Podemos aplicar a Lei de Gauss
#+BEGIN_EXPORT latex
\begin{align*}
  \int \mathbf{E}\cdot d\mathbf{S} = \frac{Q_{in}}{\varepsilon_0}.
\end{align*}
#+END_EXPORT
Veja que, para um fio reto infinito carregado uniformemente com
densidade de carga $\lambda$, cada ponto $(x,y,z)$ tem um ponto oposto
$(x,y,-z)$ com mesma carga. Assim, na componente $z$, não pode haver
campo elétrico. Portanto, o campo elétrico deve ter apenas componentes
das direções $\hat x$ e $\hat y$.

 Com um pouco mais de análise, vemos que o campo na verdade é na direção
/radial/ $\hat\rho$. Assim,
#+BEGIN_EXPORT latex
\begin{align}
  \label{eq:1}
  \oint\mathbf E\cdot d\mathbf S &= |\mathbf E| 2\pi rL = \frac{Q_{in}}{\varepsilon_0}\\
                         &= \frac 1{\varepsilon_0}\int_{fio} dV \lambda\\
                         &= \frac {\lambda}{\varepsilon_0}\int_{fio} dV\\
                         &= \frac{\lambda\pi a^2L}{\varepsilon_0}\\
  |\mathbf E| &= \frac{\lambda a^2}{2\varepsilon_0 r}\\
  \mathbf E &= \hat\rho\frac{\lambda a^2}{2\varepsilon_0 r}.
\end{align}
#+END_EXPORT

* Questão 2
Num metal (condutor), o campo elétrico no interior do material é
necessariamente nulo; caso contrário, campo movimentaria eternamente as
cargas do metal. Mostre que as cargas elétricas num objeto metálico
somente podem estar na superfície do objeto. /Sugestão. Dado um ponto/
/$P$ no interior do objeto, considere uma pequena superfície esférica,/
/imaginária, centrada em $P$. Aplique a Lei de Gauss a essa/
/superfície./

#+BEGIN_EXPORT latex
\begin{figure}[h!]
  \centering
  \includegraphics[scale=0.3]{imagens/ex-2.png}
  \caption{Em azul, um condutor sólido qualquer. Em branco, a
    superfície gaussiana de raio $r$ interna ao condutor. }
  \label{fig:ex-2}
\end{figure}
#+END_EXPORT

Considerando uma superfície gaussiana esférica de raio $r$ interna ao
condutor, como visto na Figura ref:fig:ex-2, podemos ver que 
#+BEGIN_EXPORT latex
\begin{align*}
  \oint \mathbf E\cdot d\mathbf S &= \frac{Q_{in}}{\varepsilon_0}.
\end{align*}
Por construção, $\mathbf E \equiv 0$ dentro do condutor. Assim, a integral
é identicamente nula. 
\begin{align*}
  0 &\equiv \frac{Q_{in}}{\varepsilon_0}\\
  \implies Q_{in} &\equiv 0.
\end{align*}
#+END_EXPORT
Contudo, caso tenhamos uma superfície gaussiana externa ao condutor,
fica claro que o campo não é necessariamente $0$, e portanto as cargas
devem se manter na superfície do condutor. 
* Questão 3
Uma placa metálica plana tem espessura uniforme $2a$ e é infinita nas
outras direções. Posiciona-se um sistema cartesiano com os eixos $x$ e
$y$ paralelos à superfície da placa, de forma que a origem esteja no
plano central da placa. Assim, uma das superfícies da placa está no
plano $z=a$, e a outra, no plano $z = -a$. Sabe-se que as duas faces da
placa estão carregadas com densidade superficial $\sigma$. Calcule o campo
elétrico num ponto sobre o eixo $z$ na posição $(0,0,z_0)$, com $z_0
>a$. Para isso, considere uma superfície imaginária cilíndrica cujo eixo
coincide com o eixo $z$ e que tem tampas (paralelas ao plano $xy$) em
$z=0$ (dentro do metal) e $z=z_0$. Aplique a lei de Gauss a essa
superfície. 

#+BEGIN_EXPORT latex
\begin{figure}[h!]
  \begin{subfigure}{0.3\textwidth}
    \centering
    \begin{tikzpicture}
      \draw (0,-0.25,0) -- (0,-0.25,2.5) -- (2.5,-0.25,2.5) -- (2.5,-0.25,0) -- (0,-0.25,0);
      \draw[fill=white,opacity=0.8] (0,0.25,0) -- (0,0.25,2.5) -- (2.5,0.25,2.5) -- (2.5,0.25,0) -- (0,0.25,0);
      \draw[fill=white,opacity=0.8] (0,-0.25,2.5) -- (0,0.25,2.5) -- (2.5,0.25,2.5) -- (2.5,-0.25,2.5) -- (0,-0.25,2.5);
      \draw[fill=white,opacity=0.8] (2.5,-0.25,2.5) -- (2.5,-0.25,0) -- (2.5,0.25,0) -- (2.5,0.25,2.5) -- (2.5,-0.25,2.5);
      \draw[opacity=0.2] (0,-0.25,0) -- (0,0.25,0);
    \end{tikzpicture}
    \caption{Placa metálica.}
    \label{fig:ex-3a}
  \end{subfigure}
  \begin{subfigure}{0.3\textwidth}
    \centering
    \begin{tikzpicture}
      \draw[very thick] (-1.5,0.25) -- (1.5,0.25);
      \draw[very thick] (-1.5,-0.25) -- (1.5,-0.25);
      \draw[->,dashed] (0,0) -- (0,.5) node[above] {$z$};
      \draw[<->] (1.5,0.25) -- (1.5,-0.25) node[above right] {$2a$};
    \end{tikzpicture}
    \caption{Vista lateral da placa.}
    \label{fig:ex-3b}
  \end{subfigure}
  \begin{subfigure}{0.3\textwidth}
    \centering
    \begin{tikzpicture}
      \draw (-1.25,-1.25) -- (-1.25,1.25) -- (-1.25,1.25) -- (1.25,1.25) -- (1.25,-1.25) -- (-1.25,-1.25);
      \draw[->,dashed] (0,0) -- (.5,0) node[right] {$x$};
      \draw[->,dashed] (0,0) -- (0,.5) node[above] {$y$};
    \end{tikzpicture}
    \caption{Vista superior da placa.}
    \label{fig:ex-3c}
  \end{subfigure}
  \caption{Diagrama das questões 3 e 4.}
\end{figure}
#+END_EXPORT
Fazendo uma superfície gaussiana cilíndrica com tampas em $z=0$ e
$z=z_0$, e sabendo que o campo de uma placa infinita é na direção
perpendicular ($\hat z$), temos 
#+BEGIN_EXPORT latex
\begin{figure}[h!]
  \centering
  \begin{tikzpicture}
    \draw[dashed] (0.3,0.25,0) arc (0:180:0.4 and 0.2);
    \draw[dashed] (0.3,0.25,0) -- (0.3,-0.8,0);
    \draw[dashed] (-0.5,0.25,0) -- (-0.5,-0.8,0);
    \draw[fill=white, opacity=0.7] (-1.25,0.25,1.25) -- (1.25,0.25,1.25) -- (1.25,0.25,-1.25) -- (-1.25,0.25,-1.25) -- (-1.25,0.25,1.25);
    \draw[dashed] (0.3,0.25,0) arc (0:-180:0.4 and 0.2);
    \draw[dashed] (0.3,1,0) arc (0:360:0.4 and 0.2);
    \draw[dashed] (0.3,-0.8,0) arc (0:360:0.4 and 0.2);
    \draw[dashed] (0.3,0.25,0) -- (0.3,1,0);
    \draw[dashed] (-0.5,0.25,0) -- (-0.5,1,0);
    \draw[dashed] (0,1,0) -- (1,1,0) node[right] {$z=z_0>a$};
    \draw[dashed] (0,-0.8,0) -- (1,-0.8,0) node[right] {$z=0$};
  \end{tikzpicture}  
\caption{Superfície gaussiana sobre uma das superfícies da placa metálica.}
\end{figure}
#+END_EXPORT 
#+BEGIN_EXPORT latex
\begin{align*}
  \oint\mathbf E\cdot d\mathbf S &= \frac{Q_{in}}{\varepsilon_0} = \frac{\sigma\pi r^2}{\varepsilon_0}\\
  |\mathbf E| \pi r^2 &= \frac{\sigma\pi r^2}{\varepsilon_0}\\
  |\mathbf E| &= \frac{\sigma}{\varepsilon_0}, z>a.
\end{align*}
#+END_EXPORT
O campo dentro da placa, por ser metálica, é nulo.
* Questão 4
Repita o problema anterior, mas agora considere uma superfície
imaginária cilíndrica como a do problema anterior, exceto que as tampas
estão em $z=-z_0$ e $z=z_0$.

Agora, faremos a superfície gaussiana maior que a espessura da placa,
como na Figura ref:fig:ex-4. 
#+BEGIN_EXPORT latex
\begin{figure}[h!]
  \centering
  \begin{tikzpicture}
    \draw[dashed] (0.3,0.25,0) arc (0:180:0.4 and 0.2);
    \draw[dashed] (0.3,-0.25,0) arc (0:180:0.4 and 0.2);
    \draw[dashed] (0.3,0.25,0) -- (0.3,-1.2,0);
    \draw[dashed] (-0.5,0.25,0) -- (-0.5,-1.2,0);
    \draw[fill=white, opacity=0.7] (-1.25,-0.25,1.25) -- (1.25,-0.25,1.25) -- (1.25,-0.25,-1.25) -- (-1.25,-0.25,-1.25) -- (-1.25,-0.25,1.25);
    \draw[fill=white, opacity=0.7] (-1.25,0.25,1.25) -- (1.25,0.25,1.25) -- (1.25,0.25,-1.25) -- (-1.25,0.25,-1.25) -- (-1.25,0.25,1.25);
    \draw[dashed] (0.3,0.25,0) arc (0:-180:0.4 and 0.2);
    \draw[dashed] (0.3,-0.25,0) arc (0:-180:0.4 and 0.2);
    \draw[dashed] (0.3,1,0) arc (0:360:0.4 and 0.2);
    \draw[dashed] (0.3,-1.2,0) arc (0:360:0.4 and 0.2);
    \draw[dashed] (0.3,0.25,0) -- (0.3,1,0);
    \draw[dashed] (-0.5,0.25,0) -- (-0.5,1,0);
    \draw[dashed] (0,1,0) -- (1,1,0) node[right] {$z=z_0>a$};
    \draw[dashed] (0,-1.2,0) -- (1,-1.2,0) node[right] {$z=-z_0$};
  \end{tikzpicture}
  \caption{Superfície gaussiana sobre as duas superfícies da placa metálica.}
  \label{fig:ex-4}
\end{figure}
#+END_EXPORT 
O campo que sai por cima da placa é em $\hat z$, enquanto o campo que
sai por baixo é $-\hat z$. Além disso, as áreas são orientadas para cima
em $z=z_0$ e para baixo em $z=-z_0$. Somando-se os campos,
#+BEGIN_EXPORT latex
\begin{align*}
  \oint\mathbf E \cdot d\mathbf S &= \frac{Q_{in}}{\varepsilon_0} = \frac{2\sigma\pi r^2}{\varepsilon_0}\\
  2|\mathbf E| \pi r^2 &= \frac{2\sigma\pi r^2}{\varepsilon_0}\\
  |\mathbf E| &= \frac{\sigma}{\varepsilon_0}.
\end{align*}
#+END_EXPORT
* Questão 5
Uma superfície esférica de raio $R$ está uniformemente carregada com
carga $Q$. Calcule o campo elétrico que ela produz a uma distância $r>R$
de seu centro. /Sugestão. Aplique a Lei de Gauss a uma superfície/
/imaginária de raio $r$, esférica e concêntrica com a superfície/ 
/carregada/.

#+BEGIN_EXPORT latex
\begin{figure}[h!]
  \centering
  \begin{tikzpicture}
    \draw[dotted, opacity=0.3] (3,0,0) arc (0:180:3 and 0.9);
    \draw[fill=red!30,opacity=0.8] (0,0,0) circle (1);
    \draw[dashed] (0,0,0) circle (3);
    \draw[dashed] (1,0,0) arc (0:-180:1 and 0.3);
    \draw[dashed, opacity=0.3] (1,0,0) arc (0:180:1 and 0.3);
    \draw (0,0,0) -- (1,0,0) node[above left] {$R$};
    \draw[dotted] (3,0,0) arc (0:-180:3 and 0.9);
    \draw[dashed] (0,0,0) -- (-2.2,2) node[above] {$r$};    
  \end{tikzpicture}
  \caption{Diagrama do exercício 5.}
  \label{fig:ex-5}
\end{figure}
#+END_EXPORT

Pela Lei de Gauss,
#+BEGIN_EXPORT latex
\begin{align*}
  \oint \mathbf E\cdot d\mathbf S &= \frac{Q_{in}}{\varepsilon_0}\\
  |\mathbf E| 4\pi r^2  &= \frac{Q}{\varepsilon_0}\\
  \mathbf E &=  \frac{Q}{4\pi\varepsilon_0r^2}\hat r,
\end{align*}
que é o campo de uma carga $Q$ pontual.
#+END_EXPORT
* Questão 6
Repita o problema anterior, mas agora calcule o campo no interior da
esfera ($r<R$).

Como estamos tratando de uma superfície esférica carregada, não há
cargas que estejam a uma distância $r<R$ da origem. Assim, no caso de
uma superfície gaussiana interior à superfície esférica, não há cargas
internas e portanto o campo elétrico interno é nulo.

* Questão 7
Duas superfícies esféricas concêntricas, de raios $R$ e $2R$, estão
uniformemente carregadas, com cargas $Q$ e $-Q$,
respectivamente. Calcule o campo elétrico na região $R<r<2R$, entre as
duas superfícies. 

#+BEGIN_EXPORT latex
\begin{figure}[h!]
  \centering
  \begin{tikzpicture}
    \draw[dashed, opacity=0.3] (3,0,0) arc (0:180:3 and 0.9);
    \draw[dotted, opacity=0.3] (2,0,0) arc (0:180:2 and 0.6);
    \draw[fill=white,opacity=0.8] (0,0,0) circle (1);
    \draw (0,0,0) circle (3);
    \draw[dotted, opacity=0.7] (0,0,0) circle (2);
    \draw[dotted] (0,0,0) -- (0,2,0) node[above] {$r$};
    \draw[dashed] (1,0,0) arc (0:-180:1 and 0.3);
    \draw[dashed, opacity=0.3] (1,0,0) arc (0:180:1 and 0.3);
    \draw[dotted] (2,0,0) arc (0:-180:2 and 0.6);
    \draw (0,0,0) -- (1,0,0) node[above left] {$R$};
    \draw[dashed] (3,0,0) arc (0:-180:3 and 0.9);
    \draw[dashed] (0,0,0) -- (-2.2,2) node[above left] {$2R$};    
  \end{tikzpicture}
  \caption{Diagrama do exercício 6.}
  \label{fig:ex-6}
\end{figure}
#+END_EXPORT
Na região $R<r<2R$, a única carga interna é a carga $Q$. Assim,
#+BEGIN_EXPORT latex
\begin{align*}
  \oint \mathbf E\cdot d\mathbf S &= \frac{Q}{\varepsilon_0}\\
  \mathbf E 4\pi r^2 &= \frac{Q}{\varepsilon_0}\hat r\\
  \mathbf E  &= \frac{Q}{4\pi \varepsilon_0r^2}\hat r.
\end{align*}
#+END_EXPORT

* Questão 8
No problema anterior, mostre que os campos elétricos no interior da
superfície menor e na região externa à superfície maior são nulos e
mostre em diagrama esquemático as linhas de força em todo o espaço.

Novamente, no interior da superfície de raio $R$, não há
cargas. Portanto, o campo elétrico na região interna a ela é nulo. Na
região externa a ambas as superfícies, $Q_{in}=Q-Q=0$. Portanto, $\oint\mathbf
E\cdot d\mathbf S = 0$, para qualquer superfície gaussiana escolhida, o que
significa que $\mathbf E = \mathbf0$ para pontos fora da superfície de
raio $2R$. Vemos o diagrama de forças na Figura ref:fig:ex-8-forca.

#+BEGIN_SRC ipython :session :exports code :results none :eval never-export :ipyfile "imagens/ex-8.png"
  import matplotlib.pyplot as plt
  from matplotlib.pyplot import figure
  import numpy as np
  figure(dpi=200,figsize=(4,4))

  def semicircle(r, x):
      return np.sqrt(r**2-x**2)

  def reta(theta):
      x = np.linspace(1,2,10)
      return x*np.cos(theta)

  r1 = 1
  r2 = 2
  x = np.linspace(-r1,r1,100)
  plt.plot(x,semicircle(r1,x),'darkturquoise')
  plt.plot(x,-semicircle(r1,x),'darkturquoise')
  x = np.linspace(-r2,r2,100) 
  plt.plot(x,semicircle(r2,x),'orange')
  plt.plot(x,-semicircle(r2,x),'orange')
  plt.xlabel("x")
  plt.ylabel("y")

  theta = np.linspace(0,2*np.pi,16)
  r = np.linspace(r1,r2,100)
  for item in theta:
      x = r*np.cos(item)
      y = r*np.sin(item)
      plt.arrow(x[0],y[0],x[1],y[1],head_width=.1,shape='full',length_includes_head=True)
  plt.savefig("imagens/ex-8.png")
#+END_SRC

#+BEGIN_EXPORT latex
\begin{figure}[h!]
  \centering
  \includegraphics{imagens/ex-8.png}
  \caption{Diagrama das linhas de força no interior das superfícies, secção transversal.
  Os eixos estão em unidades de $R$.}
  \label{fig:ex-8-forca}
\end{figure}
#+END_EXPORT
* Questão 9
Um disco muito fino de raio $a$ está carregado com densidade superficial
uniforme \sigma{}. Escolha um sistema de coordenadas com origem no centro do
disco e eixo $z$ perpendicular ao plano do disco. Calcule o campo
elétrico num ponto $P$ com coordenadas $(0,0,z)$. Para que valor tende o
campo quando $z\rightarrow0$? Fisicamente, você acha que esse resultado faz
sentido?

#+BEGIN_EXPORT latex
\begin{figure}[h!]
  \centering
  \begin{tikzpicture}
    \draw[thick,fill=red!50,opacity=0.8] (2,0,0) arc (0:360:2 and 1);
    \draw[->] (0,0,0) -- (0,3,0) node[right] {$z$};
    \filldraw[black] (0,2.5,0) circle (2pt) node[right] {$P$};
  \end{tikzpicture}
  \caption{Diagrama da questão 9.}
  \label{fig:ex-9}
\end{figure}
#+END_EXPORT
Vamos considerar diversos anéis infinitesimais de raio $r$ e espessura
$dr$, concêntricos. Cada anel terá uma carga $dq = \sigma2\pi rdr$. O campo que
cada anel realiza sobre o ponto $P$ é
#+BEGIN_EXPORT latex
\begin{align*}
  d\mathbf E &= \frac{dq(-r\hat r+z\hat z)}{4\pi\varepsilon_0(r^2+z^2)^{3/2}}\hat z\\
             &= \frac{\sigma rdr}{2\varepsilon_0(r^2+z^2)^{3/2}}z\hat z. 
\end{align*}
#+END_EXPORT
Por argumentos de simetria, só há campo na direção $\hat z$.
Integrando sobre o raio de $0$ a $a$, temos
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf E = \frac{\sigma z\hat z}{2\varepsilon_0}\int_0^a \frac{rdr}{(r^2+z^2)^{3/2}}.
\end{align*}
#+END_EXPORT
Com a mudança de variáveis $u=r^2+z^2$, $du = 2rdr$, temos a integral
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf E &= \frac{\sigma z\hat z}{2\varepsilon_0}\frac12\int_{z^2}^{a^2+z^2} \frac{du}{u^{3/2}}\\
            &= -\frac{\sigma z\hat z}{2\varepsilon_0}\frac12 2{u^{-1/2}}\big\vert_{z^2}^{a^2+z^2}\\
            &= -\frac{\sigma z\hat z}{2\varepsilon_0}\left(\frac1{\sqrt{a^2+z^2}}-\frac1z\right).
\end{align*}
#+END_EXPORT
Com $z^2 \ll a^2$, a raiz se aproxima de a. Então
#+BEGIN_EXPORT latex
\begin{align*}
  \mathbf E &\approx -\frac{\sigma z\hat z}{2\varepsilon_0}\left(\frac1a-\frac1z\right)\\
            &= -\frac{\sigma z\hat z}{2\varepsilon_0}\left(\frac{z-a}{az}\right)\\
            &\approx -\frac{\sigma z\hat z}{2\varepsilon_0}\left(\frac{-1}{z}\right)\\
            &= \frac{\sigma \hat z}{2\varepsilon_0}.
\end{align*}
#+END_EXPORT
Quando muito próximo do disco, o campo se aproxima do campo de um plano
carregado. 
* Questão 10
Uma esfera maciça de raio $R$ tem carga elétrica uniformemente
distribuída em seu interior, de forma que a densidade volumétrica de
carga seja $\rho$. Em outras palavras, qualquer volume $\Delta V$ no interior da
esfera tem carga $\Delta q=\rho\Delta V$. Calcule o campo elétrico num ponto $P$ da
esfera a uma distância $r<R$ do centro. /Sugestão. Imagine uma/
/superfície de raio $r$ cujo centro coincida com o da esfera e aplique/
/nela a Lei de Gauss./

Utilizando a Lei de Gauss para um sistema similar ao da Figura
ref:fig:ex-5, com a esfera interna maciça, temos
#+BEGIN_EXPORT latex
\begin{align*}
  \oint \mathbf E\cdot d\mathbf S &= \frac{Q_{in}}{\varepsilon_0}\\ 
  |\mathbf E| 4\pi r^2 &= \frac{4\pi R^3\rho}{3\varepsilon_0}\\
  |\mathbf E| &= \frac{\rho R^3}{3\varepsilon_0r^2}.
\end{align*}
#+END_EXPORT
Poderíamos ter calculado o campo para pontos interiores à esfera de raio
$R$. A única diferença em relação as contas anteriores seria que
$Q_{in}=4\pi r^3 \rho/3$. Assim,
#+BEGIN_EXPORT latex
\begin{align*}
  |\mathbf E| 4\pi r^2 &= \frac{4\pi r^3\rho}{3\varepsilon_0}\\
  |\mathbf E| &= \frac{\rho r}{3\varepsilon_0}.
\end{align*}
#+END_EXPORT
Veja que o campo elétrico em tal situação é contínuo. 
#+BEGIN_SRC ipython :session  :exports code :results none :eval never-export :ipyfile "imagens/ex-10.png"
  import matplotlib.pyplot as plt
  import numpy as np
  from matplotlib.pyplot import figure
  figure(dpi=250)

  def e_dentro(r):
      return r/3

  def e_fora(r):
      return 1/(3*r**2)

  x_d = np.linspace(0,1,20)
  x_f = np.linspace(1,5,35)
  plt.plot(x_d,e_dentro(x_d))
  plt.plot(x_f,e_fora(x_f))
  plt.xlabel(r"$r/R$")
  plt.ylabel(r"$|E(r)|$ em unidades de $\rho/\varepsilon_0$.")
  plt.legend([r"$r<R$",r"$r>R$"])
  plt.savefig("imagens/ex-10.png")
#+END_SRC
#+BEGIN_EXPORT latex
\begin{figure}[h!]
  \centering
  \includegraphics[scale=0.8]{imagens/ex-10.png}
  \caption{Intensidade do campo em função da distância ao centro da esfera.}
\end{figure}
#+END_EXPORT

* vars :noexport:
# Local Variables:
# eval: (auto-fill-mode)
# eval: (flyspell-mode)
# eval: (setq org-src-window-setup 'current-window)
# eval: (org-toggle-pretty-entities)
# eval: (latex-math-mode)
# End:
